Support relative paths to manifest files
python/pyperformance pull request #194
Opened 2022-05-04 23:58 UTC by kmod

2022-05-09 22:14 UTC, ericsnowcurrently requested changes

2022-05-09 22:14 UTC, ericsnowcurrently commented on pyperformance/_manifest.py
> +    filename = os.path.abspath(filename)
I'd say drop both lines here and add `filename = _utils.resolve_file(filename)` up in `load_manifest()`.

2022-05-09 22:15 UTC, ericsnowcurrently commented
Thanks for working on this!

2022-05-11 21:18 UTC, kmod commented
Sure thing, how about this?

2022-05-11 21:54 UTC, ericsnowcurrently approved these changes
LGTM

That works for you?

2022-05-11 22:33 UTC, kmod commented
yep! I tested it and it seems to work

2022-05-11 23:17 UTC, merged

2022-05-11 23:17 UTC, ericsnowcurrently commented
Thanks, @kmod!