Add coroutines benchmark
python/pyperformance pull request #217
Opened 2022-06-16 09:17 UTC by kumaraditya303

2022-06-17 16:02 UTC, mdboom requested changes
Looks great as a microbenchmark.  Thanks.

2022-06-17 17:24 UTC, gvanrossum commented on pyperformance/data-files/benchmarks/bm_generators/run_benchmark.py
> +        for _ in iterable:
@kumaraditya303, please move this chunk to a separate PR. PRs are cheap. Confusion due to weird commit history is expensive.

2022-06-17 17:29 UTC, kumaraditya303 commented on pyperformance/data-files/benchmarks/bm_generators/run_benchmark.py
> +        for _ in iterable:
Okay, created https://github.com/python/pyperformance/pull/218

2022-06-18 01:48 UTC, gvanrossum approved these changes
Thanks, LG now.

2022-06-18 01:48 UTC, gvanrossum commented on pyperformance/data-files/benchmarks/bm_coroutines/pyproject.toml
> +name = "coroutines"
(I guess eventually the microbenchmarks will need a tag they share, but that's not for this PR.)

2022-06-18 01:48 UTC, merged